'use strict';

// file automatically generated by angular-template-cache

angular
	.module("vd-modal").run(['$templateCache', function($templateCache) {
		$templateCache.put('/src/js/templates/modal-column-content.template.html', '<div class="modal-box__column--content">\n' +
			'	<div ng-transclude class="modal-box__column__transcluded"></div>\n' +
			'	<footer class="modal-box__column__footer">\n' +
			'		<button ng-click="vc.vm.toggleSidebar()" ng-bind="vc.vm.isShowingSidebar ? \'fechar\' : \'abrir\'"></button>\n' +
			'	</footer>\n' +
			'</div>');

		$templateCache.put('/src/js/templates/modal-column-sidebar.template.html', '<div ng-class="vc.vm.isShowingSidebar ? \'modal-box__column--sidebar\' : \'modal-box__column--sidebar-collapsed\'">\n' +
			'	<div ng-transclude class="modal-box__column__transcluded"></div>\n' +
			'</div>');

		$templateCache.put('/src/js/templates/modal.template.html', '<div class="vd-modal" ng-if=\'vc.vm.modalInstances.getObjectByValue("instanceName", vc.model.instanceName) && vc.model.isOpen\'>\n' +
			'	<div class="vd-modal__overlay" ng-click="vc.model.closeModal()" ng-class="{ \'vd-modal__overlay--transparent\' : vc.model.overlayTransparent }"></div>\n' +
			'	<div ng-class="{ \'vd-modal__container\' : !vc.model.isFullscreen, \'vd-modal__container--is-fullscreen\': vc.model.isFullscreen }">\n' +
			'		<button ng-class="{ \'vd-modal__close\' : !vc.model.isFullscreen, \'vd-modal__close--is-fullscreen\': vc.model.isFullscreen }" ng-click="vc.model.closeModal()">\n' +
			'	&times;</button>\n' +
			'		<div ng-class="{ \'vd-modal__content\' : !vc.model.isFullscreen, \'vd-modal__content--is-fullscreen\': vc.model.isFullscreen }" ng-transclude></div>\n' +
			'	</div>\n' +
			'</div>');
		
		if(!Array.prototype.getObjectByValue){
		    Array.prototype.getObjectByValue = function(propertyName, propertyValue){
		        for(var i=0; i < this.length;i++){
		            var item = this[i];
		            if(item[propertyName] === propertyValue){
		                return item;
		            }
		        }
		    };
		};			
	}
]);
